spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/linechatbotddmobile}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

line:
  bot:
    channel-token: ${LINE_BOT_CHANNEL_TOKEN}
    channel-secret: ${LINE_BOT_CHANNEL_SECRET}
    handler:
      path: /callback

  admin:
    user-ids: ${LINE_ADMIN_USER_IDS}

openai:
  api:
    key: ${OPENAI_API_KEY}
    url: "https://api.openai.com/v1"
  model: "gpt-4o-mini"