package com.example.linechatbotddmobile.service.line;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DataSourceTransactionManager;
import org.springframework.jdbc.datasource.DriverManagerDataSource;

import javax.sql.DataSource;
import java.util.Map;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

class UserStateIntegrityInitializerTests {

    private JdbcTemplate jdbcTemplate;
    private UserStateIntegrityInitializer initializer;

    @BeforeEach
    void setUp() {
        String databaseUrl = environment("USER_STATE_TEST_DB_URL",
                "jdbc:h2:mem:user-state-integrity;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE");
        DataSource dataSource = new DriverManagerDataSource(
                databaseUrl,
                environment("USER_STATE_TEST_DB_USER", "sa"),
                environment("USER_STATE_TEST_DB_PASSWORD", ""));
        jdbcTemplate = new JdbcTemplate(dataSource);
        jdbcTemplate.execute("DROP TABLE IF EXISTS user_states");
        jdbcTemplate.execute(createTableSql());
        initializer = new UserStateIntegrityInitializer(
                jdbcTemplate,
                new DataSourceTransactionManager(dataSource));
    }

    @Test
    void repairsLegacyDuplicatesAndPausesTheAffectedConversation() {
        insertState(new TestState(1, "U-duplicate", "STEP_2_CAPACITY", null, "13 Pro Max", null));
        insertState(new TestState(2, "U-duplicate", "STEP_4_AGE", null, null, "256GB"));
        insertState(new TestState(3, "U-healthy", "STEP_3_PROVINCE", null, "14 Pro", "128GB"));
        jdbcTemplate.update("UPDATE user_states SET service_name = 'จำนำ iCloud' WHERE id = 2");

        initializer.repairAndConstrain();

        assertThat(countFor("U-duplicate")).isEqualTo(1);
        Map<String, Object> repaired = jdbcTemplate.queryForMap(
                "SELECT * FROM user_states WHERE line_user_id = ?", "U-duplicate");
        assertThat(repaired)
                .containsEntry("current_state", "ADMIN_MODE")
                .containsEntry("previous_state", "STEP_4_AGE")
                .containsEntry("service_name", "ผ่อนบอลลูน")
                .containsEntry("device_model", "13 Pro Max")
                .containsEntry("capacity", "256GB")
                .containsEntry("retry_count", 0)
                .containsEntry("follow_up_reminder_sent", false);

        Map<String, Object> healthy = jdbcTemplate.queryForMap(
                "SELECT * FROM user_states WHERE line_user_id = ?", "U-healthy");
        assertThat(healthy).containsEntry("current_state", "STEP_3_PROVINCE");
    }

    @Test
    void uniqueIndexRejectsFutureDuplicateRows() {
        insertState(new TestState(1, "U-unique", "STEP_1_INFO", null, null, null));
        initializer.repairAndConstrain();

        assertThatThrownBy(() ->
                insertState(new TestState(2, "U-unique", "STEP_2_CAPACITY", null, null, null)))
                .isInstanceOf(DataIntegrityViolationException.class);
    }

    @Test
    void repairCanRunMoreThanOnce() {
        insertState(new TestState(1, "U-idempotent", "STEP_2_CAPACITY", null, null, null));

        initializer.repairAndConstrain();
        initializer.repairAndConstrain();

        assertThat(countFor("U-idempotent")).isEqualTo(1);
    }

    private void insertState(TestState state) {
        jdbcTemplate.update("""
                INSERT INTO user_states (
                    id, line_user_id, service_name, current_state, previous_state,
                    capacity, device_model, retry_count, follow_up_reminder_sent
                ) VALUES (?, ?, 'ผ่อนบอลลูน', ?, ?, ?, ?, 1, TRUE)
                """, state.id(), state.userId(), state.currentState(), state.previousState(),
                state.capacity(), state.model());
    }

    private int countFor(String userId) {
        return jdbcTemplate.queryForObject(
                "SELECT COUNT(*) FROM user_states WHERE line_user_id = ?", Integer.class, userId);
    }

    private static String createTableSql() {
        return """
                CREATE TABLE user_states (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    line_user_id VARCHAR(255), service_name VARCHAR(255),
                    current_state VARCHAR(255), previous_state VARCHAR(255),
                    capacity VARCHAR(255), last_user_message TEXT,
                    device_model VARCHAR(255), full_name VARCHAR(255), province VARCHAR(255),
                    retry_count INTEGER, follow_up_reminder_started_at TIMESTAMP,
                    follow_up_reminder_sent BOOLEAN
                )
                """;
    }

    private static String environment(String name, String defaultValue) {
        String value = System.getenv(name);
        return value == null || value.isBlank() ? defaultValue : value;
    }

    private record TestState(long id, String userId, String currentState,
                             String previousState, String model, String capacity) {
    }
}
